import { useEffect, useRef } from 'react'
import * as THREE from 'three'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js'
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js'

type Props={url:string|null;playing:boolean;loop:boolean;speed:number;showSkeleton?:boolean;selectedBone?:string|null;onError?:(message:string|null)=>void}
export default function AnimationViewer({url,playing,loop,speed,showSkeleton=true,selectedBone,onError}:Props){
 const host=useRef<HTMLDivElement|null>(null),mixer=useRef<THREE.AnimationMixer|null>(null),action=useRef<THREE.AnimationAction|null>(null),model=useRef<THREE.Object3D|null>(null),selectedHelper=useRef<THREE.AxesHelper|null>(null)
 useEffect(()=>{const node=host.current;if(!node)return;const scene=new THREE.Scene();scene.background=new THREE.Color(0x11151c);const camera=new THREE.PerspectiveCamera(35,1,.01,2000);camera.position.set(2.2,1.5,3.2);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(window.devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;node.appendChild(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;scene.add(new THREE.HemisphereLight(0xffffff,0x20252e,2.2));const key=new THREE.DirectionalLight(0xffffff,2.5);key.position.set(3,5,4);scene.add(key);scene.add(new THREE.GridHelper(8,16,0x39414d,0x242a33));const clock=new THREE.Clock();let disposed=false;const resize=()=>{const w=Math.max(1,node.clientWidth),h=Math.max(1,node.clientHeight);renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()};const observer=new ResizeObserver(resize);observer.observe(node);resize();
  if(url)new GLTFLoader().load(url,gltf=>{if(disposed)return;model.current=gltf.scene;scene.add(gltf.scene);const box=new THREE.Box3().setFromObject(gltf.scene),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3()),radius=Math.max(size.length()*.55,.5);controls.target.copy(center);camera.position.set(center.x+radius*1.1,center.y+radius*.5,center.z+radius*1.7);camera.near=Math.max(radius/1000,.001);camera.far=radius*30;camera.updateProjectionMatrix();controls.update();if(showSkeleton)scene.add(new THREE.SkeletonHelper(gltf.scene));if(gltf.animations.length){const mx=new THREE.AnimationMixer(gltf.scene),ac=mx.clipAction(gltf.animations[0]);ac.play();ac.paused=!playing;ac.setLoop(loop?THREE.LoopRepeat:THREE.LoopOnce,loop?Infinity:1);ac.clampWhenFinished=!loop;mx.timeScale=speed;mixer.current=mx;action.current=ac}onError?.(null)},undefined,err=>onError?.(`Falha ao abrir GLB: ${String(err)}`));
  let frame=0;const animate=()=>{if(disposed)return;const dt=clock.getDelta();mixer.current?.update(dt);controls.update();renderer.render(scene,camera);frame=requestAnimationFrame(animate)};animate();return()=>{disposed=true;cancelAnimationFrame(frame);observer.disconnect();controls.dispose();renderer.dispose();mixer.current?.stopAllAction();mixer.current=null;action.current=null;model.current=null;renderer.domElement.remove()}},[url,showSkeleton])
 useEffect(()=>{if(action.current)action.current.paused=!playing},[playing]);useEffect(()=>{const a=action.current;if(a){a.setLoop(loop?THREE.LoopRepeat:THREE.LoopOnce,loop?Infinity:1);a.clampWhenFinished=!loop}},[loop]);useEffect(()=>{if(mixer.current)mixer.current.timeScale=speed},[speed]);useEffect(()=>{selectedHelper.current?.removeFromParent();selectedHelper.current=null;if(!selectedBone||!model.current)return;const bone=model.current.getObjectByName(selectedBone);if(!bone)return;const axes=new THREE.AxesHelper(.12);bone.add(axes);selectedHelper.current=axes;return()=>axes.removeFromParent()},[selectedBone,url]);return <div className="animationViewer" ref={host}/>
}
