import {useEffect,useRef,useState} from 'react'
import * as THREE from 'three'
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js'
import {GLTFLoader} from 'three/examples/jsm/loaders/GLTFLoader.js'
import type {BodyPoint,BreastMarkers} from './ModelViewer'
import './breast-paint.css'

export type PaintedBreastMarkers=BreastMarkers&{paint:{left:BodyPoint[];right:BodyPoint[];brush_radius:number}}
type MarkerInfo={height:number;radius_min:number;radius_max:number;radius_default:number;paint_radius_min?:number;paint_radius_max?:number;paint_radius_default?:number}
type Props={url:string;info:MarkerInfo;initial?:PaintedBreastMarkers|null;onDone:(markers:PaintedBreastMarkers)=>void;onCancel:()=>void;onError?:(message:string)=>void}
type Side='left'|'right'

function dispose(root:THREE.Object3D){root.traverse(o=>{if(!(o instanceof THREE.Mesh||o instanceof THREE.Line||o instanceof THREE.Points))return;o.geometry?.dispose();const mats=Array.isArray(o.material)?o.material:[o.material];mats.forEach(m=>m.dispose())})}
function average(points:BodyPoint[]):BodyPoint{const n=Math.max(1,points.length),sum=points.reduce((a,p)=>[a[0]+p[0],a[1]+p[1],a[2]+p[2]] as BodyPoint,[0,0,0] as BodyPoint);return [sum[0]/n,sum[1]/n,sum[2]/n]}
function distance(a:BodyPoint,b:BodyPoint){return Math.hypot(a[0]-b[0],a[1]-b[1],a[2]-b[2])}

export default function BreastPaintDialog({url,info,initial,onDone,onCancel,onError}:Props){
 const host=useRef<HTMLDivElement|null>(null),model=useRef<THREE.Object3D|null>(null),paintGroup=useRef<THREE.Group|null>(null)
 const [side,setSide]=useState<Side>('left'),[paintMode,setPaintMode]=useState(true),[loading,setLoading]=useState(true)
 const [strokes,setStrokes]=useState<Record<Side,BodyPoint[]>>({left:initial?.paint?.left??[],right:initial?.paint?.right??[]})
 const minBrush=info.paint_radius_min??info.height*.006,maxBrush=info.paint_radius_max??info.height*.055,defaultBrush=initial?.paint?.brush_radius??info.paint_radius_default??info.height*.018
 const [brush,setBrush]=useState(Math.min(maxBrush,Math.max(minBrush,defaultBrush)))
 const sideRef=useRef(side);sideRef.current=side
 const paintModeRef=useRef(paintMode);paintModeRef.current=paintMode
 const brushRef=useRef(brush);brushRef.current=brush

 useEffect(()=>{const el=host.current;if(!el)return
  const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(38,1,.01,10000),renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;el.appendChild(renderer.domElement)
  const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.screenSpacePanning=true
  scene.add(new THREE.HemisphereLight(0xeaf0ff,0x272a34,2.2));const key=new THREE.DirectionalLight(0xffffff,2.8);key.position.set(4,6,5);scene.add(key);const rim=new THREE.DirectionalLight(0x9d8cff,1.4);rim.position.set(-4,3,-5);scene.add(rim)
  const annotations=new THREE.Group();scene.add(annotations);paintGroup.current=annotations
  const raycaster=new THREE.Raycaster(),mouse=new THREE.Vector2();let drawing=false,lastScreen:{x:number;y:number}|null=null
  const hitPoint=(event:PointerEvent)=>{if(!model.current)return null;const rect=renderer.domElement.getBoundingClientRect();mouse.set((event.clientX-rect.left)/rect.width*2-1,-(event.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(mouse,camera);const hit=raycaster.intersectObject(model.current,true).find(x=>x.object instanceof THREE.Mesh);return hit?.point.toArray() as BodyPoint|undefined}
  const addPoint=(event:PointerEvent,force=false)=>{if(!paintModeRef.current)return;if(!force&&lastScreen&&Math.hypot(event.clientX-lastScreen.x,event.clientY-lastScreen.y)<5)return;const point=hitPoint(event);if(!point)return;lastScreen={x:event.clientX,y:event.clientY};const active=sideRef.current;setStrokes(old=>{const list=old[active];if(list.length>=512)return old;if(list.length&&distance(list[list.length-1],point)<Math.max(brushRef.current*.22,info.height*.0015))return old;return {...old,[active]:[...list,point]}})}
  const down=(event:PointerEvent)=>{if(event.button!==0||!paintModeRef.current)return;drawing=true;lastScreen=null;renderer.domElement.setPointerCapture(event.pointerId);addPoint(event,true)}
  const move=(event:PointerEvent)=>{if(drawing)addPoint(event)}
  const up=(event:PointerEvent)=>{if(!drawing)return;drawing=false;lastScreen=null;try{renderer.domElement.releasePointerCapture(event.pointerId)}catch{}}
  renderer.domElement.addEventListener('pointerdown',down);renderer.domElement.addEventListener('pointermove',move);renderer.domElement.addEventListener('pointerup',up);renderer.domElement.addEventListener('pointercancel',up)
  const resize=()=>{const w=Math.max(1,el.clientWidth),h=Math.max(1,el.clientHeight);renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()};const ro=new ResizeObserver(resize);ro.observe(el);resize()
  let cancelled=false;new GLTFLoader().load(url,gltf=>{if(cancelled){dispose(gltf.scene);return}scene.add(gltf.scene);model.current=gltf.scene;gltf.scene.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(gltf.scene),center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3());let up=new THREE.Vector3(0,1,0),front=new THREE.Vector3(0,0,1),right=new THREE.Vector3(1,0,0);const bones=new Map<string,THREE.Vector3>();gltf.scene.traverse(o=>{if(o instanceof THREE.Bone)bones.set(o.name.toLowerCase().replace(/[^a-z0-9]/g,'').replace(/^mixamorig/,''),o.getWorldPosition(new THREE.Vector3()))});const head=bones.get('head'),hips=bones.get('hips'),left=bones.get('leftarm'),r=bones.get('rightarm');if(head&&hips&&left&&r){up=head.clone().sub(hips).normalize();right=left.clone().sub(r);right.addScaledVector(up,-right.dot(up)).normalize();front=right.clone().cross(up).normalize()}const max=Math.max(size.x,size.y,size.z,.1),fov=THREE.MathUtils.degToRad(camera.fov),d=(max/(2*Math.tan(fov/2)))*1.45;camera.up.copy(up);camera.position.copy(center).add(front.multiplyScalar(d));controls.target.copy(center);controls.update();setLoading(false)},undefined,e=>{setLoading(false);onError?.(`Falha ao abrir a base para pintura: ${e instanceof Error?e.message:String(e)}`)})
  let frame=0;const animate=()=>{controls.enabled=!paintModeRef.current;controls.update();renderer.render(scene,camera);frame=requestAnimationFrame(animate)};animate()
  return()=>{cancelled=true;cancelAnimationFrame(frame);ro.disconnect();controls.dispose();renderer.domElement.removeEventListener('pointerdown',down);renderer.domElement.removeEventListener('pointermove',move);renderer.domElement.removeEventListener('pointerup',up);renderer.domElement.removeEventListener('pointercancel',up);if(model.current)dispose(model.current);dispose(annotations);renderer.dispose();renderer.domElement.remove();model.current=null;paintGroup.current=null}
 },[url,info.height,onError])

 useEffect(()=>{const group=paintGroup.current;if(!group)return;dispose(group);group.clear();for(const s of ['left','right'] as const){const pts=strokes[s].map(p=>new THREE.Vector3(...p));if(!pts.length)continue;const color=s==='left'?0x38d7e7:0xffb84b,geometry=new THREE.BufferGeometry().setFromPoints(pts);const line=new THREE.Line(geometry,new THREE.LineBasicMaterial({color,transparent:true,opacity:.95,depthTest:false}));line.renderOrder=20;group.add(line);const points=new THREE.Points(geometry.clone(),new THREE.PointsMaterial({color,size:5,sizeAttenuation:false,transparent:true,opacity:.85,depthTest:false}));points.renderOrder=21;group.add(points)}} ,[strokes])

 const finish=()=>{if(strokes.left.length<3||strokes.right.length<3)return;const left=average(strokes.left),right=average(strokes.right),spread=(points:BodyPoint[],center:BodyPoint)=>Math.max(...points.map(p=>distance(p,center))),derived=Math.max(spread(strokes.left,left),spread(strokes.right,right))+brush*.75,radius=Math.min(info.radius_max,Math.max(info.radius_min,derived));onDone({left,right,radius,paint:{left:strokes.left,right:strokes.right,brush_radius:brush}})}
 const valid=strokes.left.length>=3&&strokes.right.length>=3
 return <div className="breastPaintModal" role="dialog" aria-modal="true" aria-label="Pintar área dos seios"><div className="breastPaintTop"><div><strong>Pintar área dos seios</strong><span>Pinte sobre a superfície que deve participar do volume. Não pinte o esterno nem a barriga.</span></div><button onClick={onCancel}>Cancelar</button></div><div className="breastPaintCanvas" ref={host}>{loading&&<div className="breastPaintLoading">Carregando base…</div>}</div><aside className="breastPaintPanel"><div className="breastPaintMode"><button className={paintMode?'selected':''} onClick={()=>setPaintMode(true)}>Pintar</button><button className={!paintMode?'selected':''} onClick={()=>setPaintMode(false)}>Navegar</button></div><p>Use <b>Navegar</b> para girar/zoom. Volte para <b>Pintar</b> e arraste o mouse sobre a malha.</p><div className="breastPaintSides">{(['left','right'] as const).map(s=><button key={s} className={side===s?'selected':''} onClick={()=>{setSide(s);setPaintMode(true)}}>{s==='left'?'Seio esquerdo':'Seio direito'} · {strokes[s].length}</button>)}</div><label>Tamanho do pincel · {Math.round(brush/info.height*1000)/10}%<input type="range" min={minBrush} max={maxBrush} step={info.height*.001} value={brush} onChange={e=>setBrush(Number(e.target.value))}/></label><button onClick={()=>setStrokes(x=>({...x,[side]:[]}))}>Limpar lado atual</button><button onClick={()=>setStrokes({left:[],right:[]})}>Limpar tudo</button><div className="breastPaintLegend"><span><i className="left"/>Esquerdo</span><span><i className="right"/>Direito</span></div><button className="primary" disabled={!valid} onClick={finish}>Usar área pintada</button>{!valid&&<small>Pinte pelo menos três pontos em cada lado. Para resultado melhor, cubra a área com vários traços.</small>}</aside></div>
}
