import { ChangeEvent,useEffect,useMemo,useState } from 'react'
import { ArrowLeft,Bone,Download,FileUp,Pause,Play,RefreshCw,RotateCcw,Save,Upload,Waypoints } from 'lucide-react'
import AnimationViewer from './components/AnimationViewer'
import './components/animation.css'
type Source={kind:string;asset_id:string;preparation_id:string;customization_id?:string;revision_id?:string;label:string;proportions_changed:boolean;updated_at:number};type BoneRow={name:string;parent:string|null;deform:boolean;semantic?:string|null;length:number};type Caps={armature:string;target_signature:string;bones:BoneRow[];semantic_matches:Record<string,string>;structural_layer:{present:boolean};source?:Source;limitations?:string[]};type Rotation={x:number;y:number;z:number};type Rotations=Record<string,Rotation>;type TaskEvent={type:string;value?:number;message:string;result?:any};type AnimReport={status:string;compatibility?:Record<string,number>;blockers?:string[];warnings?:string[];root_motion_note?:string;validation?:Record<string,any>;proportion_changes_checked?:boolean;structural_layer_preserved?:boolean;source_action?:string;retargeting_method?:string}
const API='http://127.0.0.1:8000',WS='ws://127.0.0.1:8000',MODEL=new Set(['fbx','glb','gltf']),RESOURCE=new Set(['bin','png','jpg','jpeg','webp','ktx2']);const ext=(n:string)=>n.split('.').pop()?.toLowerCase()??''
async function req(path:string,init?:RequestInit){const r=await fetch(API+path,init);if(!r.ok){let m=`HTTP ${r.status}`;try{m=(await r.json()).detail??m}catch{}throw new Error(m)}return r.json()}
function watch(id:string,on:(e:TaskEvent)=>void){const s=new WebSocket(`${WS}/ws/tasks/${id}`);s.onopen=()=>s.send('ready');s.onmessage=e=>on(JSON.parse(e.data));return s}
export default function AnimationWorkspace({onBack}:{onBack:()=>void}){
 const [sources,setSources]=useState<Source[]>([]),[sourceKey,setSourceKey]=useState(''),[sessionId,setSessionId]=useState<string|null>(null),[caps,setCaps]=useState<Caps|null>(null),[rotations,setRotations]=useState<Rotations>({}),[selectedBone,setSelectedBone]=useState(''),[poses,setPoses]=useState<Record<string,any>>({}),[poseName,setPoseName]=useState(''),[preview,setPreview]=useState<string|null>(null),[poseBlend,setPoseBlend]=useState<string|null>(null),[animBlend,setAnimBlend]=useState<string|null>(null),[animationFiles,setAnimationFiles]=useState<File[]>([]),[rootMotion,setRootMotion]=useState<'preserve'|'in_place'>('preserve'),[report,setReport]=useState<AnimReport|null>(null),[playing,setPlaying]=useState(true),[loop,setLoop]=useState(true),[speed,setSpeed]=useState(1),[status,setStatus]=useState('Selecione uma base preparada ou uma revisão corporal.'),[progress,setProgress]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null)
 const selected=useMemo(()=>sources.find((s,i)=>sourceValue(s,i)===sourceKey)??null,[sources,sourceKey]);const current=selectedBone?(rotations[selectedBone]??{x:0,y:0,z:0}):{x:0,y:0,z:0}
 const refresh=async()=>{try{const d=await req('/api/stage5/sources');setSources(d.items??[]);if(!sourceKey&&d.items?.[0])setSourceKey(sourceValue(d.items[0],0))}catch(e){setError(String(e))}};useEffect(()=>{void refresh()},[])
 const run=(id:string,done:(r:any)=>void)=>{const s=watch(id,e=>{setStatus(e.message);if(e.type==='progress')setProgress(e.value??0);if(e.type==='error'){setError(e.message+(e.result?.report?.blockers?.length?` · ${e.result.report.blockers.join(' ')}`:''));setBusy(false);s.close()}if(e.type==='success'){done(e.result);setProgress(100);setBusy(false);s.close()}});s.onerror=()=>{setError('WebSocket interrompido.');setBusy(false)}}
 const prepare=async()=>{if(!selected)return;setBusy(true);setError(null);setProgress(0);setReport(null);setRotations({});try{const payload={kind:selected.kind,asset_id:selected.asset_id,preparation_id:selected.preparation_id,customization_id:selected.customization_id,revision_id:selected.revision_id};const d=await req('/api/stage5/sessions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});setSessionId(d.session_id);run(d.task_id,r=>{setCaps(r.capabilities);const first=r.capabilities.bones?.find((b:BoneRow)=>b.semantic==='head')??r.capabilities.bones?.[0];setSelectedBone(first?.name??'');setPreview(API+r.preview_url+`?v=${Date.now()}`);void req(`/api/stage5/sessions/${r.session_id}/poses`).then(x=>setPoses(x.poses??{}))})}catch(e){setError(String(e));setBusy(false)}}
 const axis=(a:keyof Rotation,v:number)=>{if(!selectedBone)return;setRotations(x=>({...x,[selectedBone]:{...(x[selectedBone]??{x:0,y:0,z:0}),[a]:v}}))}
 const applyPose=async()=>{if(!sessionId)return;setBusy(true);setError(null);setProgress(0);try{const d=await req(`/api/stage5/sessions/${sessionId}/pose`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rotations})});run(d.task_id,r=>{setPreview(API+r.preview_url+`?v=${Date.now()}`);setPoseBlend(API+r.blend_url);setReport(null)})}catch(e){setError(String(e));setBusy(false)}}
 const restore=()=>{setRotations({});setPoseBlend(null);setReport(null);if(sessionId)setPreview(`${API}/api/stage5/sessions/${sessionId}/preview.glb?v=${Date.now()}`)}
 const savePose=async()=>{if(!sessionId||!poseName.trim())return;try{await req(`/api/stage5/sessions/${sessionId}/poses`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:poseName,rotations})});const d=await req(`/api/stage5/sessions/${sessionId}/poses`);setPoses(d.poses??{});setPoseName('')}catch(e){setError(String(e))}}
 const loadPose=(n:string)=>{const p=poses[n];if(p?.rotations_degrees)setRotations(p.rotations_degrees)};const pick=(e:ChangeEvent<HTMLInputElement>)=>setAnimationFiles(Array.from(e.target.files??[]))
 const importAnim=async()=>{if(!sessionId||!animationFiles.length)return;const ms=animationFiles.filter(f=>MODEL.has(ext(f.name))),rs=animationFiles.filter(f=>RESOURCE.has(ext(f.name)));if(ms.length!==1){setError('Selecione exatamente um FBX/GLB/GLTF de animação e, se necessário, suas dependências.');return}setBusy(true);setError(null);setProgress(0);setReport(null);const form=new FormData();form.append('model',ms[0]);rs.forEach(f=>form.append('resources',f));form.append('root_motion',rootMotion);try{const d=await req(`/api/stage5/sessions/${sessionId}/animations`,{method:'POST',body:form});run(d.task_id,r=>{setReport(r.report);if(r.preview_url){setPreview(API+r.preview_url+`?v=${Date.now()}`);setPlaying(true)}setAnimBlend(r.blend_url?API+r.blend_url:null)})}catch(e){setError(String(e));setBusy(false)}}
 const downloadPose=()=>{const b=new Blob([JSON.stringify({format_version:1,target_signature:caps?.target_signature,rotations_degrees:rotations},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='bodiez-pose.json';a.click();URL.revokeObjectURL(a.href)}
 return <div className="stage5Shell"><header className="stage5Topbar"><button className="secondary" onClick={onBack}><ArrowLeft size={15}/> Voltar</button><div><strong>Esqueleto · Poses · Animações</strong><span>Etapa 5 · Blender como referência</span></div><div className="stage5Badge">{caps?.structural_layer?.present?'proporções personalizadas preservadas':'referência preparada'}</div></header>
 <aside className="stage5Left panel"><div className="panelTitle">Fonte do personagem</div><button className="secondary" onClick={()=>void refresh()}><RefreshCw size={14}/> Atualizar</button><select value={sourceKey} onChange={e=>{setSourceKey(e.target.value);setSessionId(null);setCaps(null);setPreview(null);setReport(null)}}><option value="">Selecione…</option>{sources.map((s,i)=><option key={sourceValue(s,i)} value={sourceValue(s,i)}>{s.label}{s.proportions_changed?' · proporções alteradas':''}</option>)}</select><button className="primary" disabled={!selected||busy} onClick={()=>void prepare()}><Waypoints size={15}/> Preparar Etapa 5</button><div className="progress"><div style={{width:`${progress}%`}}/></div><p className="muted">{status}</p>{error&&<div className="errorBox">{error}</div>}{poseBlend&&<a className="downloadLink" href={poseBlend}><Download size={14}/> Baixar pose .blend</a>}{animBlend&&<a className="downloadLink" href={animBlend}><Download size={14}/> Baixar animação .blend</a>}</aside>
 <main className="stage5Viewer"><AnimationViewer url={preview} playing={playing} loop={loop} speed={speed} showSkeleton selectedBone={selectedBone} onError={setError}/>{report?.status==='ready'&&<div className="playbackBar"><button onClick={()=>setPlaying(v=>!v)}>{playing?<Pause size={16}/>:<Play size={16}/>}</button><label><input type="checkbox" checked={loop} onChange={e=>setLoop(e.target.checked)}/> repetir</label><label>velocidade <input type="range" min="0.25" max="2" step="0.05" value={speed} onChange={e=>setSpeed(Number(e.target.value))}/><strong>{speed.toFixed(2)}×</strong></label></div>}</main>
 <aside className="stage5Right panel">{!caps?<div className="stage5Empty"><Bone size={30}/><strong>Prepare uma fonte</strong><span>O Blender descobrirá os ossos reais antes de liberar controles.</span></div>:<><section className="stage5Section"><div className="sectionHeading"><span>Esqueleto</span><small>{caps.bones.length} ossos</small></div><select value={selectedBone} onChange={e=>setSelectedBone(e.target.value)}>{caps.bones.map(b=><option key={b.name} value={b.name}>{b.semantic?`${b.semantic} · `:''}{b.name}</option>)}</select>{(['x','y','z'] as const).map(a=><label className="boneSlider" key={a}><div><span>Rotação {a.toUpperCase()}</span><strong>{Math.round(current[a])}°</strong></div><input type="range" min="-180" max="180" step="1" value={current[a]} disabled={busy} onChange={e=>axis(a,Number(e.target.value))}/></label>)}<div className="stage5Actions"><button className="secondary" onClick={restore}><RotateCcw size={15}/> Referência</button><button className="primary" disabled={busy} onClick={()=>void applyPose()}><Bone size={15}/> Aplicar pose</button></div></section>
 <section className="stage5Section"><div className="sectionHeading"><span>Poses</span><small>JSON</small></div>{Object.keys(poses).length>0&&<select defaultValue="" onChange={e=>e.target.value&&loadPose(e.target.value)}><option value="">Carregar pose salva…</option>{Object.keys(poses).sort().map(n=><option key={n}>{n}</option>)}</select>}<div className="poseSave"><input value={poseName} onChange={e=>setPoseName(e.target.value)} placeholder="Nome da pose"/><button onClick={()=>void savePose()}><Save size={15}/></button><button onClick={downloadPose}><Download size={15}/></button></div></section>
 <section className="stage5Section"><div className="sectionHeading"><span>Animações Mixamo</span><small>FBX / GLB / GLTF</small></div><label className="filePicker"><FileUp size={16}/><span>{animationFiles.length?`${animationFiles.length} arquivo(s) selecionado(s)`:'Selecionar animação'}</span><input type="file" multiple accept=".fbx,.glb,.gltf,.bin,.png,.jpg,.jpeg,.webp,.ktx2" onChange={pick}/></label><label className="rootMotion"><span>Movimento da raiz</span><select value={rootMotion} onChange={e=>setRootMotion(e.target.value as any)}><option value="preserve">Preservar</option><option value="in_place">In-place (remove X/Y)</option></select></label><button className="primary" disabled={busy||!animationFiles.length} onClick={()=>void importAnim()}><Upload size={15}/> Inspecionar e retargetear</button>{report&&<AnimationReport report={report}/>}</section>{caps.limitations?.map(x=><p className="microNote" key={x}>{x}</p>)}</>}</aside></div>
}
function sourceValue(s:Source,i:number){return `${s.kind}:${s.asset_id}:${s.preparation_id}:${s.customization_id??''}:${s.revision_id??''}:${i}`}
function AnimationReport({report}:{report:AnimReport}){const c=report.compatibility??{};return <div className={`animationReport ${report.status}`}><strong>{report.status==='ready'?'Animação validada':report.status==='review_required'?'Revisão recomendada':'Retargeting bloqueado'}</strong><div className="metricGrid"><span>Ossos mapeados<b>{c.mapped_bones??'—'}</b></span><span>Hierarquia<b>{c.hierarchy_ratio!=null?`${Math.round(Number(c.hierarchy_ratio)*100)}%`:'—'}</b></span><span>Rest pose média<b>{c.mean_rest_orientation_delta_degrees!=null?`${Number(c.mean_rest_orientation_delta_degrees).toFixed(1)}°`:'—'}</b></span><span>Validação<b>{report.validation?.passed===true?'ok':report.validation?'revisar':'—'}</b></span></div>{report.proportion_changes_checked&&<p>✓ Testada sobre as proporções corporais atuais.</p>}{report.structural_layer_preserved&&<p>✓ Camada estrutural preservada.</p>}{report.root_motion_note&&<p>{report.root_motion_note}</p>}{report.blockers?.map(x=><p className="reportError" key={x}>{x}</p>)}{report.warnings?.map(x=><p className="reportWarning" key={x}>{x}</p>)}</div>}
