import type {ReactNode} from 'react'
import {useEffect,useMemo,useState} from 'react'
import {AlertTriangle,ArrowLeft,Box,CheckCircle2,Download,FileArchive,FileJson,Image,PackageCheck,RefreshCw,Save,Upload} from 'lucide-react'
import ModelViewer from './components/ModelViewer'
import './components/export.css'

type Source={kind:string;label:string;updated_at:number;asset_id?:string;preparation_id?:string;customization_id?:string;revision_id?:string;session_id?:string;animation_id?:string;has_animation:boolean;has_pose:boolean;body_editable:boolean}
type ProjectRow={project_id:string;name:string;created_at:number;source:Record<string,any>;editability:Record<string,any>}
type ProjectManifest={format:string;format_version:number;project_id:string;name:string;created_at:number;source:Record<string,any>;body:Record<string,any>;poses:Record<string,any>;animation:Record<string,any>;editability:Record<string,any>;export_policy:Record<string,any>}
type Warning={scope:string;code:string;message:string}
type ExportReport={source_mode?:string;interchange_semantics?:string;features?:Record<string,any>;warnings?:Warning[];outputs?:Record<string,any>}
type TaskEvent={type:string;value?:number;message:string;result?:any}

const API='http://127.0.0.1:8000',WS='ws://127.0.0.1:8000'
async function req(path:string,init?:RequestInit){const r=await fetch(API+path,init);if(!r.ok){let m=`HTTP ${r.status}`;try{m=(await r.json()).detail??m}catch{}throw new Error(m)}return r.json()}
function watch(id:string,on:(e:TaskEvent)=>void){const s=new WebSocket(`${WS}/ws/tasks/${id}`);s.onopen=()=>s.send('ready');s.onmessage=e=>on(JSON.parse(e.data));return s}
function sourceKey(s:Source,i:number){return `${s.kind}:${s.asset_id??''}:${s.preparation_id??''}:${s.customization_id??''}:${s.revision_id??''}:${s.session_id??''}:${s.animation_id??''}:${i}`}
function sourcePayload(s:Source){return {kind:s.kind,asset_id:s.asset_id,preparation_id:s.preparation_id,customization_id:s.customization_id,revision_id:s.revision_id,session_id:s.session_id,animation_id:s.animation_id}}

export default function ExportWorkspace({onBack}:{onBack:()=>void}){
 const [sources,setSources]=useState<Source[]>([]),[projects,setProjects]=useState<ProjectRow[]>([]),[sourceChoice,setSourceChoice]=useState(''),[projectChoice,setProjectChoice]=useState(''),[project,setProject]=useState<ProjectManifest|null>(null),[name,setName]=useState('Meu personagem Bodiez'),[formats,setFormats]=useState<Record<string,boolean>>({blend:true,glb:true,fbx:false,png:true}),[resolution,setResolution]=useState(1024),[progress,setProgress]=useState(0),[status,setStatus]=useState('Selecione uma fonte final para salvar.'),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[report,setReport]=useState<ExportReport|null>(null),[files,setFiles]=useState<Record<string,string>>({}),[preview,setPreview]=useState<string|null>(null),[viewerError,setViewerError]=useState<string|null>(null)
 const selectedSource=useMemo(()=>sources.find((s,i)=>sourceKey(s,i)===sourceChoice)??null,[sources,sourceChoice])
 const refresh=async()=>{setError(null);try{const [s,p]=await Promise.all([req('/api/stage7/sources'),req('/api/stage7/projects')]);setSources(s.items??[]);setProjects(p.items??[]);if(!sourceChoice&&s.items?.[0])setSourceChoice(sourceKey(s.items[0],0))}catch(e){setError(String(e))}}
 useEffect(()=>{void refresh()},[])
 const loadProject=async(id:string)=>{if(!id){setProjectChoice('');setProject(null);return}setError(null);try{const data=await req(`/api/stage7/projects/${id}`);setProject(data);setProjectChoice(id);setName(data.name??'Projeto Bodiez');setFiles({});setReport(null);setPreview(null)}catch(e){setError(String(e))}}
 const create=async()=>{if(!selectedSource)return;setBusy(true);setError(null);setStatus('Salvando projeto versionado e copiando source.blend…');try{const d=await req('/api/stage7/projects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,source:sourcePayload(selectedSource)})});setProject(d.project);setProjectChoice(d.project_id);setFiles({});setReport(null);setPreview(null);setStatus('Projeto salvo. Agora escolha as saídas de exportação.');await refresh()}catch(e){setError(String(e))}finally{setBusy(false)}}
 const toggle=(fmt:string)=>setFormats(x=>({...x,[fmt]:!x[fmt]}))
 const exportNow=async()=>{if(!project)return;const chosen=Object.entries(formats).filter(([,v])=>v).map(([k])=>k);if(!chosen.length){setError('Selecione pelo menos um formato.');return}setBusy(true);setError(null);setProgress(0);setFiles({});setReport(null);setStatus('Enfileirando exportação no Blender…');try{const d=await req(`/api/stage7/projects/${project.project_id}/exports`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({formats:chosen,resolution})});const s=watch(d.task_id,e=>{setStatus(e.message);if(e.type==='progress')setProgress(e.value??0);if(e.type==='error'){setError(e.message);if(e.result?.report)setReport(e.result.report);setBusy(false);s.close()}if(e.type==='success'){const out:Record<string,string>={};for(const [fmt,path] of Object.entries(e.result?.files??{}))out[fmt]=API+String(path);setFiles(out);setReport(e.result?.report??null);setPreview(out.glb?`${out.glb}?v=${Date.now()}`:null);setProgress(100);setBusy(false);s.close()}});s.onerror=()=>{setError('WebSocket da exportação foi interrompido.');setBusy(false)}}catch(e){setError(String(e));setBusy(false)}}
 const bodyCount=project?.body?.values?Object.keys(project.body.values).length:0,poseCount=project?.poses?.library?Object.keys(project.poses.library).length:0,hasAnim=Boolean(project?.animation&&Object.keys(project.animation).length)
 return <div className="stage7Shell"><header className="stage7Topbar"><button className="secondary" onClick={onBack}><ArrowLeft size={15}/> Voltar</button><div><strong>Salvar e exportar</strong><span>Etapa 7 · projeto editável + intercâmbio + render</span></div><div className="stage7Badge"><PackageCheck size={14}/>{project?'projeto versionado':'aguardando projeto'}</div></header>
 <aside className="stage7Left panel"><div className="panelTitle">Projeto Bodiez</div><button className="secondary" onClick={()=>void refresh()}><RefreshCw size={14}/> Atualizar fontes</button><label className="stage7Label">Fonte final</label><select value={sourceChoice} onChange={e=>setSourceChoice(e.target.value)}><option value="">Selecione…</option>{sources.map((s,i)=><option key={sourceKey(s,i)} value={sourceKey(s,i)}>{s.label}</option>)}</select><input className="stage7Name" value={name} maxLength={80} onChange={e=>setName(e.target.value)} placeholder="Nome do projeto"/><button className="primary" disabled={!selectedSource||busy} onClick={()=>void create()}><Save size={15}/> Salvar novo projeto</button><div className="stage7Divider"/><label className="stage7Label">Projetos já salvos</label><select value={projectChoice} onChange={e=>void loadProject(e.target.value)}><option value="">Selecione…</option>{projects.map(p=><option key={p.project_id} value={p.project_id}>{p.name} · {p.project_id.slice(0,6)}</option>)}</select>{project&&<><a className="downloadLink" href={`${API}/api/stage7/projects/${project.project_id}/project.bodiez.json`}><FileJson size={14}/> Baixar projeto .bodiez.json</a><a className="downloadLink" href={`${API}/api/stage7/projects/${project.project_id}/source.blend`}><FileArchive size={14}/> Baixar source.blend</a></>}<div className="stage7Progress"><div style={{width:`${progress}%`}}/></div><p className="muted">{status}</p>{error&&<div className="errorBox">{error}</div>}{viewerError&&<div className="errorBox">{viewerError}</div>}</aside>
 <main className="stage7Viewer"><ModelViewer url={preview} wireframe={false} skeleton={true} viewRequest={{name:'perspective',nonce:0}} onViewerError={setViewerError}/>{!preview&&<div className="stage7ViewerEmpty"><Box size={38}/><strong>Prévia de exportação</strong><span>Exporte GLB para inspecionar a saída de intercâmbio aqui.</span></div>}{project&&<div className="stage7ProjectStrip"><span>{project.name}</span><span>formato v{project.format_version}</span><span>{project.source.kind}</span></div>}</main>
 <aside className="stage7Right panel">{!project?<div className="stage7Empty"><PackageCheck size={30}/><strong>Salve ou carregue um projeto</strong><span>O manifesto preserva parâmetros, poses, referências e versão antes de qualquer exportação.</span></div>:<><section className="stage7Section"><div className="sectionHeading"><span>Estado preservado</span><small>projeto</small></div><div className="stage7Stats"><div><b>{bodyCount}</b><span>parâmetros corporais</span></div><div><b>{poseCount}</b><span>poses salvas</span></div><div><b>{hasAnim?'sim':'não'}</b><span>animação ativa</span></div><div><b>v{project.format_version}</b><span>formato do projeto</span></div></div><div className="stage7Policy"><CheckCircle2 size={14}/><span><b>.blend é autoritativo/editável.</b> GLB/FBX não preservam a semântica dos controles Bodiez.</span></div></section><section className="stage7Section"><div className="sectionHeading"><span>Exportação</span><small>Blender</small></div><FormatRow checked={formats.blend} on={()=>toggle('blend')} icon={<FileArchive size={15}/>} title="BLEND editável" note="Rig, modifiers, shape keys, actions e metadados do Blender."/><FormatRow checked={formats.glb} on={()=>toggle('glb')} icon={<Box size={15}/>} title="GLB" note="Intercâmbio: rig, materiais, animações e morphs compatíveis."/><FormatRow checked={formats.fbx} on={()=>toggle('fbx')} icon={<Upload size={15}/>} title="FBX" note="Intercâmbio; blend shapes e materiais dependem do software de destino."/><FormatRow checked={formats.png} on={()=>toggle('png')} icon={<Image size={15}/>} title="PNG transparente" note="Render RGBA do estado atual."/>{formats.png&&<label className="stage7Resolution"><span>Resolução PNG</span><select value={resolution} onChange={e=>setResolution(Number(e.target.value))}><option value={512}>512 × 512</option><option value={1024}>1024 × 1024</option><option value={2048}>2048 × 2048</option></select></label>}<button className="primary stage7ExportButton" disabled={busy} onClick={()=>void exportNow()}><Upload size={15}/> Exportar no Blender</button></section>{Object.keys(files).length>0&&<section className="stage7Section"><div className="sectionHeading"><span>Arquivos gerados</span><small>download</small></div>{Object.entries(files).map(([fmt,url])=><a className="stage7File" key={fmt} href={url}><Download size={14}/><span>{fmt.toUpperCase()}</span></a>)}</section>}{report&&<Report report={report}/>}</>}</aside></div>
}

function FormatRow({checked,on,icon,title,note}:{checked:boolean;on:()=>void;icon:ReactNode;title:string;note:string}){return <label className={`stage7Format ${checked?'active':''}`}><input type="checkbox" checked={checked} onChange={on}/>{icon}<span><strong>{title}</strong><small>{note}</small></span></label>}
function Report({report}:{report:ExportReport}){const f=report.features??{},warnings=report.warnings??[];return <section className="stage7Section"><div className="sectionHeading"><span>Relatório</span><small>{warnings.length} aviso(s)</small></div><div className="stage7FeatureGrid"><span>malhas<b>{f.mesh_count??'—'}</b></span><span>armatures<b>{f.armature_count??'—'}</b></span><span>shape keys<b>{f.shape_key_count??'—'}</b></span><span>actions<b>{f.action_count??'—'}</b></span></div>{warnings.length===0?<div className="stage7Ok"><CheckCircle2 size={14}/> Nenhum aviso de portabilidade detectado.</div>:warnings.map((w,i)=><div className="stage7Warning" key={`${w.code}:${i}`}><AlertTriangle size={14}/><div><strong>{w.scope}</strong><span>{w.message}</span></div></div>)}</section>}
