import {useEffect,useMemo,useState} from 'react'
import {AlertTriangle,ArrowLeft,Box,CheckCircle2,Download,RefreshCw,ShieldCheck,XCircle} from 'lucide-react'
import ModelViewer from './components/ModelViewer'
import './components/final-validation.css'

type ExportRow={export_id:string;created_at:number;requested_formats:string[];files:Record<string,boolean>;has_report:boolean}
type Target={project_id:string;name:string;created_at:number;source:Record<string,any>;editability:Record<string,any>;exports:ExportRow[]}
type Check={group:string;key:string;label:string;status:'pass'|'warn'|'fail';evidence:string;metrics?:Record<string,any>}
type Report={format_version:number;project_id:string;validation_id:string;export_id:string|null;verdict:'pass'|'pass_with_warnings'|'blocked';summary:{passed:number;warnings:number;failures:number;total:number};checks:Check[];metrics?:Record<string,any>;limitations:string[];flow:Record<string,string>}
type TaskEvent={type:string;value?:number;message:string;result?:Report}
const API='http://127.0.0.1:8000',WS='ws://127.0.0.1:8000'
async function req(path:string,init?:RequestInit){const r=await fetch(API+path,init);if(!r.ok){let m=`HTTP ${r.status}`;try{m=(await r.json()).detail??m}catch{}throw new Error(m)}return r.json()}
function watch(id:string,on:(event:TaskEvent)=>void){const s=new WebSocket(`${WS}/ws/tasks/${id}`);s.onopen=()=>s.send('ready');s.onmessage=e=>on(JSON.parse(e.data));return s}

export default function FinalValidationWorkspace({onBack}:{onBack:()=>void}){
 const [targets,setTargets]=useState<Target[]>([]),[projectId,setProjectId]=useState(''),[exportId,setExportId]=useState(''),[report,setReport]=useState<Report|null>(null),[validationId,setValidationId]=useState<string|null>(null),[progress,setProgress]=useState(0),[status,setStatus]=useState('Selecione um projeto salvo da Etapa 7.'),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[viewerError,setViewerError]=useState<string|null>(null)
 const target=useMemo(()=>targets.find(t=>t.project_id===projectId)??null,[targets,projectId])
 const selectedExport=useMemo(()=>target?.exports.find(e=>e.export_id===exportId)??null,[target,exportId])
 const preview=target&&selectedExport?.files.glb?`${API}/api/stage7/projects/${target.project_id}/exports/${selectedExport.export_id}/files/glb`:null
 const refresh=async()=>{setError(null);try{const d=await req('/api/stage8/targets');setTargets(d.items??[])}catch(e){setError(String(e))}}
 useEffect(()=>{void refresh()},[])
 const chooseProject=(id:string)=>{setProjectId(id);setExportId('');setReport(null);setValidationId(null);setProgress(0);setStatus(id?'Escolha uma exportação para comparação, ou valide apenas o projeto.':'Selecione um projeto salvo da Etapa 7.')}
 const run=async()=>{if(!target)return;setBusy(true);setError(null);setViewerError(null);setReport(null);setProgress(0);setStatus('Iniciando validação final…');try{const d=await req(`/api/stage8/projects/${target.project_id}/validations`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({export_id:exportId||null})});setValidationId(d.validation_id);const s=watch(d.task_id,e=>{setStatus(e.message);if(e.type==='progress')setProgress(e.value??0);if(e.type==='error'){setError(e.message);setBusy(false);s.close()}if(e.type==='success'){setReport(e.result??null);setProgress(100);setBusy(false);s.close()}});s.onerror=()=>{setError('WebSocket da validação foi interrompido.');setBusy(false)}}catch(e){setError(String(e));setBusy(false)}}
 const groups=['project','scene','deformation','exports','resources']
 return <div className="stage8Shell"><header className="stage8Topbar"><button className="secondary" onClick={onBack}><ArrowLeft size={15}/> Voltar</button><div><strong>Validação final do fluxo</strong><span>Etapa 8 · evidência de projeto, Blender e exportações reimportadas</span></div><Verdict report={report}/></header>
 <aside className="stage8Left panel"><div className="panelTitle">Alvo de validação</div><button className="secondary" onClick={()=>void refresh()}><RefreshCw size={14}/> Atualizar projetos</button><label className="stage8Label">Projeto salvo</label><select value={projectId} onChange={e=>chooseProject(e.target.value)}><option value="">Selecione…</option>{targets.map(t=><option key={t.project_id} value={t.project_id}>{t.name} · {t.project_id.slice(0,6)}</option>)}</select><label className="stage8Label">Exportação para comparar</label><select value={exportId} disabled={!target} onChange={e=>{setExportId(e.target.value);setReport(null);setValidationId(null)}}><option value="">Somente projeto/source.blend</option>{target?.exports.map(e=><option key={e.export_id} value={e.export_id}>{e.export_id.slice(0,6)} · {Object.entries(e.files).filter(([,v])=>v).map(([k])=>k.toUpperCase()).join(' + ')||'sem arquivos'}</option>)}</select><button className="primary stage8Run" disabled={!target||busy} onClick={()=>void run()}><ShieldCheck size={15}/> Executar validação final</button><div className="stage8Progress"><div style={{width:`${progress}%`}}/></div><p className="muted">{status}</p>{error&&<div className="errorBox">{error}</div>}{viewerError&&<div className="errorBox">{viewerError}</div>}{report&&validationId&&<a className="downloadLink" href={`${API}/api/stage8/projects/${report.project_id}/validations/${validationId}/report.json`}><Download size={14}/> Baixar relatório final JSON</a>}<Flow target={target} exportSelected={Boolean(exportId)} report={report}/></aside>
 <main className="stage8Viewer"><ModelViewer url={preview} wireframe={false} skeleton={true} viewRequest={{name:'perspective',nonce:0}} onViewerError={setViewerError}/>{!preview&&<div className="stage8ViewerEmpty"><Box size={38}/><strong>Comparação visual opcional</strong><span>Escolha uma exportação que contenha GLB para abrir a mesma saída validada.</span></div>}{report&&<div className={`stage8Summary ${report.verdict}`}><strong>{report.verdict==='pass'?'APROVADO':report.verdict==='pass_with_warnings'?'APROVADO COM AVISOS':'BLOQUEADO'}</strong><span>{report.summary.passed} passaram · {report.summary.warnings} avisos · {report.summary.failures} falhas</span></div>}</main>
 <aside className="stage8Right panel">{!report?<div className="stage8Empty"><ShieldCheck size={31}/><strong>Relatório ainda não executado</strong><span>O Blender reabrirá o source.blend, testará articulações e reimportará GLB/FBX quando selecionados.</span></div>:<>{groups.map(group=><CheckGroup key={group} group={group} checks={report.checks.filter(c=>c.group===group)}/>)}<section className="stage8Section"><div className="sectionHeading"><span>Limitações reais</span><small>{report.limitations.length}</small></div>{report.limitations.length?report.limitations.map((l,i)=><div className="stage8Limitation" key={i}><AlertTriangle size={13}/><span>{l}</span></div>):<div className="stage8Ok"><CheckCircle2 size={13}/> Nenhuma limitação adicional registrada.</div>}</section></>}</aside></div>
}
function Verdict({report}:{report:Report|null}){if(!report)return <div className="stage8Badge neutral">aguardando validação</div>;if(report.verdict==='pass')return <div className="stage8Badge pass"><CheckCircle2 size={13}/> aprovado</div>;if(report.verdict==='pass_with_warnings')return <div className="stage8Badge warn"><AlertTriangle size={13}/> aprovado com avisos</div>;return <div className="stage8Badge fail"><XCircle size={13}/> bloqueado</div>}
function Flow({target,exportSelected,report}:{target:Target|null;exportSelected:boolean;report:Report|null}){const edit=target?.editability??{};const rows=[['Importar/preparar',Boolean(target),'linhagem do projeto'],['Personalizar',Boolean(edit.body_parameters_recorded),edit.body_parameters_recorded?'parâmetros registrados':'não usado nesta linhagem'],['Posar',Boolean(edit.pose_data_recorded),edit.pose_data_recorded?'pose registrada':'não usado nesta linhagem'],['Animar',Boolean(edit.animation_data_recorded),edit.animation_data_recorded?'animação registrada':'não usado nesta linhagem'],['Salvar/reabrir',Boolean(report),'source.blend reaberto pelo Blender'],['Exportar',exportSelected,exportSelected?'conjunto selecionado para reimportação':'comparação não selecionada']];return <div className="stage8Flow"><strong>Fluxo coberto</strong>{rows.map(([label,on,note])=><div key={String(label)}><span className={on?'done':'optional'}>{on?'✓':'—'}</span><p><b>{String(label)}</b><small>{String(note)}</small></p></div>)}</div>}
function CheckGroup({group,checks}:{group:string;checks:Check[]}){if(!checks.length)return null;const names:Record<string,string>={project:'Projeto/reabertura',scene:'Cena · escala/orientação',deformation:'Deformação',exports:'Exportações reimportadas',resources:'Recursos'};return <section className="stage8Section"><div className="sectionHeading"><span>{names[group]??group}</span><small>{checks.length}</small></div>{checks.map(c=><div className={`stage8Check ${c.status}`} key={`${c.group}:${c.key}`}>{c.status==='pass'?<CheckCircle2 size={14}/>:c.status==='warn'?<AlertTriangle size={14}/>:<XCircle size={14}/>}<div><strong>{c.label}</strong><span>{c.evidence}</span></div></div>)}</section>}
