import {useEffect,useMemo,useRef,useState} from 'react'
import {ArrowLeft,CheckCircle2,Download,Eye,Redo2,RefreshCw,RotateCcw,SlidersHorizontal,Undo2,Zap} from 'lucide-react'
import Stage6Viewer,{MorphApplication} from './components/Stage6Viewer'
import './components/stage6.css'

type Ready={asset_id:string;preparation_id:string;mode:string|null;updated_at:number}
type Values=Record<string,number>;type Bindings=Record<string,string|undefined>
type Spec={label:string;kind:string;min:number;max:number;default:number}
type Source={source_id:string;type:string;display_name:string;control_hint:string|null;driven:boolean;targets?:{mesh:string;key:string}[]}
type Caps={controls:Record<string,{enabled:boolean;reason?:string|null;generated_assisted?:boolean}>;morph_sources:Source[];default_bindings:Bindings;control_specs:Record<string,Spec>;builtin_presets:Record<string,Values>}
type Snap={values:Values;bindings:Bindings};type Event={type:string;value?:number;message:string;result?:any}
const API='http://127.0.0.1:8000',WS='ws://127.0.0.1:8000',LIMIT=40
async function req(path:string,init?:RequestInit){const r=await fetch(API+path,init);if(!r.ok){let m=`HTTP ${r.status}`;try{m=(await r.json()).detail??m}catch{}throw new Error(m)}return r.json()}
function watch(id:string,on:(e:Event)=>void){const s=new WebSocket(`${WS}/ws/tasks/${id}`);s.onopen=()=>s.send('ready');s.onmessage=e=>on(JSON.parse(e.data));return s}
const copy=(v:Values,b:Bindings):Snap=>({values:{...v},bindings:{...b}})
const token=()=>crypto.randomUUID().replaceAll('-','')

export default function Stage6Workspace({onBack}:{onBack:()=>void}){
 const [ready,setReady]=useState<Ready[]>([]),[key,setKey]=useState(''),[bodyId,setBodyId]=useState<string|null>(null),[caps,setCaps]=useState<Caps|null>(null),[values,setValues]=useState<Values>({}),[bindings,setBindings]=useState<Bindings>({}),[baseline,setBaseline]=useState<string|null>(null),[live,setLive]=useState<string|null>(null),[blend,setBlend]=useState<string|null>(null),[selectedControl,setSelectedControl]=useState<string|null>(null),[before,setBefore]=useState(false),[undoStack,setUndo]=useState<Snap[]>([]),[redoStack,setRedo]=useState<Snap[]>([]),[generation,setGeneration]=useState(0),[active,setActive]=useState(0),[progress,setProgress]=useState(0),[status,setStatus]=useState('Selecione uma preparação aprovada.'),[error,setError]=useState<string|null>(null),[preparing,setPreparing]=useState(false),[finalizing,setFinalizing]=useState(false),[morphReport,setMorphReport]=useState({requested:0,matched:0})
 const client=useRef(token()),desired=useRef(0),valuesRef=useRef(values),bindingsRef=useRef(bindings),editRef=useRef<Snap|null>(null);valuesRef.current=values;bindingsRef.current=bindings
 const selected=useMemo(()=>ready.find(x=>`${x.asset_id}:${x.preparation_id}`===key)??null,[ready,key]),specs=caps?.control_specs??{}
 const structural=useMemo(()=>Object.keys(specs).filter(n=>specs[n].kind==='structural'),[caps]),morphs=useMemo(()=>Object.keys(specs).filter(n=>specs[n].kind!=='structural'),[caps])
 const morphApps=useMemo<MorphApplication[]>(()=>{if(!caps)return[];const idx=new Map(caps.morph_sources.map(s=>[s.source_id,s])),out:MorphApplication[]=[];for(const n of morphs){const sid=bindings[n],s=sid?idx.get(sid):null;if(!s||s.driven)continue;for(const t of s.targets??[])out.push({...t,value:values[n]??specs[n]?.default??0})}return out},[caps,bindings,values,morphs,specs])
 const defaults=(c:Caps)=>Object.fromEntries(Object.entries(c.control_specs).map(([n,s])=>[n,s.default])) as Values
 const refresh=async()=>{try{const d=await req('/api/stage4/ready-preparations');setReady(d.items??[]);if(!key&&d.items?.[0])setKey(`${d.items[0].asset_id}:${d.items[0].preparation_id}`)}catch(e){setError(String(e))}}
 useEffect(()=>{void refresh()},[])
 const dirtyStructural=()=>{desired.current+=1;setGeneration(desired.current);setStatus('Alteração estrutural aguardando debounce…')}
 const restoreSnap=(s:Snap)=>{const changed=structural.some(n=>(valuesRef.current[n]??specs[n]?.default)!==(s.values[n]??specs[n]?.default));setValues({...s.values});setBindings({...s.bindings});if(changed)dirtyStructural()}
 const begin=()=>{if(!editRef.current)editRef.current=copy(valuesRef.current,bindingsRef.current)}
 const end=()=>{const old=editRef.current;editRef.current=null;if(!old)return;const now=copy(valuesRef.current,bindingsRef.current);if(JSON.stringify(old)!==JSON.stringify(now)){setUndo(x=>[...x,old].slice(-LIMIT));setRedo([])}}
 const undo=()=>{if(editRef.current){const old=editRef.current;editRef.current=null;setRedo(x=>[copy(valuesRef.current,bindingsRef.current),...x].slice(0,LIMIT));restoreSnap(old);return}if(!undoStack.length)return;const old=undoStack.at(-1)!;setUndo(undoStack.slice(0,-1));setRedo(x=>[copy(valuesRef.current,bindingsRef.current),...x].slice(0,LIMIT));restoreSnap(old)}
 const redo=()=>{if(!redoStack.length)return;const next=redoStack[0];setRedo(redoStack.slice(1));setUndo(x=>[...x,copy(valuesRef.current,bindingsRef.current)].slice(-LIMIT));restoreSnap(next)}
 useEffect(()=>{const f=(e:KeyboardEvent)=>{if(!(e.ctrlKey||e.metaKey))return;if(e.key.toLowerCase()==='z'&&!e.shiftKey){e.preventDefault();undo()}else if(e.key.toLowerCase()==='y'||(e.key.toLowerCase()==='z'&&e.shiftKey)){e.preventDefault();redo()}};window.addEventListener('keydown',f);return()=>window.removeEventListener('keydown',f)})
 const change=(n:string,v:number)=>{setSelectedControl(n);setValues(x=>({...x,[n]:v}));if(specs[n]?.kind==='structural')dirtyStructural()}
 const bind=(n:string,sid:string|undefined)=>{const old=copy(valuesRef.current,bindingsRef.current);setUndo(x=>[...x,old].slice(-LIMIT));setRedo([]);setSelectedControl(n);setBindings(x=>({...x,[n]:sid}))}
 const preset=(p:Values)=>{const old=copy(valuesRef.current,bindingsRef.current),next={...defaults(caps!),...p};setUndo(x=>[...x,old].slice(-LIMIT));setRedo([]);const changed=structural.some(n=>next[n]!==valuesRef.current[n]);setValues(next);if(changed)dirtyStructural()}
 const reset=()=>{if(!caps)return;const old=copy(valuesRef.current,bindingsRef.current),next=defaults(caps);setUndo(x=>[...x,old].slice(-LIMIT));setRedo([]);const changed=structural.some(n=>next[n]!==valuesRef.current[n]);setValues(next);setBindings({...caps.default_bindings});if(changed)dirtyStructural()}
 const prepare=async()=>{if(!selected)return;setPreparing(true);setError(null);setProgress(0);try{const d=await req(`/api/assets/${selected.asset_id}/preparations/${selected.preparation_id}/customizations`,{method:'POST'});setBodyId(d.customization_id);const s=watch(d.task_id,e=>{setStatus(e.message);if(e.type==='progress')setProgress(e.value??0);if(e.type==='error'){setError(e.message);setPreparing(false);s.close()}if(e.type==='success'){const c=e.result.capabilities as Caps,u=API+e.result.preview_url+`?v=${Date.now()}`;setCaps(c);setValues(defaults(c));setBindings({...c.default_bindings});setBaseline(u);setLive(u);setBlend(null);setSelectedControl(Object.keys(c.control_specs)[0]??null);setUndo([]);setRedo([]);desired.current=0;setGeneration(0);setPreparing(false);setProgress(100);setStatus('Morphs respondem localmente; estrutura usa Blender com debounce.');s.close()}})}catch(e){setError(String(e));setPreparing(false)}}
 const sync=async(gen:number)=>{if(!selected||!bodyId||!caps)return;setActive(x=>x+1);try{const d=await req(`/api/stage6/assets/${selected.asset_id}/preparations/${selected.preparation_id}/customizations/${bodyId}/live`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({client_token:client.current,generation:gen,values:valuesRef.current,bindings:bindingsRef.current})});const s=watch(d.task_id,e=>{if(e.type==='progress'&&gen===desired.current){setProgress(e.value??0);setStatus(e.message)}if(e.type==='error'){setActive(x=>Math.max(0,x-1));if(gen===desired.current)setError(e.message);s.close()}if(e.type==='success'){setActive(x=>Math.max(0,x-1));const r=e.result??{};if(!r.stale&&gen===desired.current&&r.preview_url){setLive(API+r.preview_url+`?v=${Date.now()}`);setStatus('Blender sincronizado; câmera e seleção preservadas.');setProgress(100)}else if(gen!==desired.current)setStatus('Resultado ultrapassado ignorado.');s.close()}});s.onerror=()=>{setActive(x=>Math.max(0,x-1));if(gen===desired.current)setError('WebSocket da sincronização interrompido.')}}catch(e){setActive(x=>Math.max(0,x-1));if(gen===desired.current)setError(String(e))}}
 useEffect(()=>{if(!bodyId||!caps||generation<1)return;const t=window.setTimeout(()=>void sync(generation),900);return()=>window.clearTimeout(t)},[generation,bodyId,caps])
 const finalize=async()=>{if(!selected||!bodyId)return;end();setFinalizing(true);setError(null);try{const d=await req(`/api/assets/${selected.asset_id}/preparations/${selected.preparation_id}/customizations/${bodyId}/apply`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({values:valuesRef.current,bindings:bindingsRef.current})});const s=watch(d.task_id,e=>{setStatus(e.message);if(e.type==='progress')setProgress(e.value??0);if(e.type==='error'){setError(e.message);setFinalizing(false);s.close()}if(e.type==='success'){if(e.result.preview_url)setLive(API+e.result.preview_url+`?v=${Date.now()}`);setBlend(e.result.blend_url?API+e.result.blend_url:null);setFinalizing(false);setProgress(100);s.close()}})}catch(e){setError(String(e));setFinalizing(false)}}
 return <div className="stage6Shell"><header className="stage6Topbar"><button className="secondary" onClick={onBack}><ArrowLeft size={15}/> Voltar</button><div><strong>Atualização e experiência de uso</strong><span>Etapa 6 · morph local + Blender debounced</span></div><div className={`stage6Sync ${active?'busy':''}`}><Zap size={13}/>{active?'Blender sincronizando':'prévia responsiva'}</div></header>
 <aside className="stage6Left panel"><div className="panelTitle">Base corporal</div><button className="secondary" onClick={()=>void refresh()}><RefreshCw size={14}/> Atualizar</button><select value={key} onChange={e=>{setKey(e.target.value);setBodyId(null);setCaps(null);setBaseline(null);setLive(null);setBlend(null)}}><option value="">Selecione…</option>{ready.map(x=><option key={`${x.asset_id}:${x.preparation_id}`} value={`${x.asset_id}:${x.preparation_id}`}>{x.asset_id.slice(0,8)} · {x.mode??'preparada'}</option>)}</select><button className="primary" disabled={!selected||preparing} onClick={()=>void prepare()}><SlidersHorizontal size={15}/> Preparar experiência</button><div className="historyToolbar"><button disabled={!undoStack.length&&!editRef.current} onClick={undo}><Undo2 size={14}/> Desfazer</button><button disabled={!redoStack.length} onClick={redo}><Redo2 size={14}/> Refazer</button></div><button className={`compareButton ${before?'active':''}`} disabled={!baseline} onClick={()=>setBefore(v=>!v)}><Eye size={14}/>{before?'Mostrando antes':'Comparar antes/depois'}</button><div className="stage6Progress"><div style={{width:`${progress}%`}}/></div><p className="muted">{status}</p>{error&&<div className="errorBox">{error}</div>}{blend&&<a className="downloadLink" href={blend}><Download size={14}/> Baixar revisão .blend</a>}<div className="stage6TechNote"><CheckCircle2 size={15}/><div><strong>Morphs não iniciam Blender</strong><span>Shape keys equivalentes são locais; rig/estrutura agrupa mudanças por 900 ms.</span></div></div></aside>
 <main className="stage6Viewer"><Stage6Viewer url={before?baseline:(live??baseline)} morphApplications={before?[]:morphApps} showSkeleton onError={setError} onMorphReport={setMorphReport}/><div className="stage6Overlay"><span>{before?'ANTES · baseline limpa':'DEPOIS · estado atual'}</span>{!before&&morphReport.requested>0&&<span>{morphReport.matched}/{morphReport.requested} morph targets locais</span>}{selectedControl&&<span>seleção: {specs[selectedControl]?.label??selectedControl}</span>}</div></main>
 <aside className="stage6Right panel">{!caps?<div className="stage6Empty"><SlidersHorizontal size={30}/><strong>Prepare uma base</strong><span>Os controles reais serão inspecionados antes da edição.</span></div>:<><section className="stage6Section"><div className="sectionHeading"><span>Tipos corporais</span><small>histórico</small></div><div className="presetGrid">{Object.entries(caps.builtin_presets).map(([n,p])=><button key={n} onClick={()=>preset(p)}>{n}</button>)}</div></section><section className="stage6Section"><div className="sectionHeading"><span>Estrutura</span><small>Blender · debounce</small></div>{structural.map(n=><Slider key={n} name={n} caps={caps} values={values} selected={selectedControl===n} begin={begin} end={end} select={setSelectedControl} change={change}/>)}</section><section className="stage6Section"><div className="sectionHeading"><span>Volume / silhueta</span><small>Three.js imediato</small></div>{morphs.map(n=>{const cap=caps.controls[n],opts=caps.morph_sources.filter(s=>!s.driven&&(s.type==='existing'||s.control_hint===n)),sid=bindings[n]??'';return <div className={`stage6Morph ${selectedControl===n?'selected':''}`} key={n} onClick={()=>setSelectedControl(n)}><div className="morphHeader"><strong>{specs[n].label}</strong>{cap?.generated_assisted&&<span className="generatedPill">assistido</span>}</div><select value={sid} onChange={e=>bind(n,e.target.value||undefined)}><option value="">{n==='breast_size'?'Mapear shape key real / não usar':'Sem fonte de morph'}</option>{opts.map(s=><option key={s.source_id} value={s.source_id}>{s.type==='generated'?'Gerado':'Existente'} · {s.display_name}</option>)}</select>{sid?<Slider name={n} caps={caps} values={values} selected={selectedControl===n} begin={begin} end={end} select={setSelectedControl} change={change}/>:<p className="microNote">{cap?.reason??'Selecione uma fonte real.'}</p>}</div>})}</section><div className="stage6Actions"><button className="secondary" onClick={reset}><RotateCcw size={15}/> Restaurar</button><button className="primary" disabled={finalizing} onClick={()=>void finalize()}><SlidersHorizontal size={15}/> Aplicar definitivo</button></div><p className="microNote">A revisão definitiva sempre parte da baseline limpa.</p></>}</aside></div>
}
function Slider({name,caps,values,selected,begin,end,select,change}:{name:string;caps:Caps;values:Values;selected:boolean;begin:()=>void;end:()=>void;select:(n:string)=>void;change:(n:string,v:number)=>void}){const s=caps.control_specs[name],c=caps.controls[name];if(!s)return null;if(!c?.enabled&&s.kind==='structural')return <div className="disabledControl"><strong>{s.label}</strong><span>{c?.reason??'Indisponível.'}</span></div>;const v=values[name]??s.default;return <label className={`stage6Slider ${selected?'selected':''}`} onClick={()=>select(name)}><div><span>{s.label}</span><strong>{s.kind==='structural'?`${Math.round(v*100)}%`:`${v>=0?'+':''}${Math.round(v*100)}%`}</strong></div><input type="range" min={s.min} max={s.max} step="0.01" value={v} onPointerDown={begin} onPointerUp={end} onKeyDown={begin} onKeyUp={end} onChange={e=>change(name,Number(e.target.value))}/></label>}
